[package]
name = "avb"
version = "0.1.9"
edition = "2021"

[dependencies]
toml = "0.7.0"
serde = { version= "1.0.152", features = ["derive"] }
quicli = "0.4"
structopt = "0.2"
uid = "0.1.7"
env_logger = "0.10.0"
log = "0.4.20"
