name: Rust

on:
  push:
    tags:
      - v[0-9]+.*

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: taiki-e/create-gh-release-action@v1
        with:
          changelog: CHANGELOG.md
          token: ${{ secrets.GITHUB_TOKEN }}

  upload-assets:
    strategy:
      matrix:
        include:
        - target: aarch64-unknown-linux-gnu
          os: ubuntu-latest
        - target: aarch64-apple-darwin
          os: macos-latest
        - target: x86_64-unknown-linux-gnu
          os: ubuntu-latest
        - target: x86_64-apple-darwin
          os: macos-latest
        # Universal macOS binary is supported as universal-apple-darwin.
        - target: universal-apple-darwin
          os: macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Build and upload Rust binary to GitHub Releases
        uses: taiki-e/upload-rust-binary-action@v1.12.0
        with:
          zip: windows
          bin: aws-vault-firefox-container
          token: ${{ secrets.GITHUB_TOKEN }}
